### ISSUE TITLE
dask-array-basics

### ISSUE THREAD

**Issue by ricleal** [blaze/dask-examples#13]
Hello,

Just wanted to let you know that while running the `dask-array-basics.ipynb`, I got the following error:

``` python
$ ipython
Python 2.7.11 (default, Dec 15 2015, 16:46:19) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import dask.array as da

In [2]: x = da.fromfunction(lambda i, j, k: i + j + k**2, chunks=(5, 512, 512), shape=(100, 2048, 2048), dtype='f8')

In [3]: x.to_hdf5('myfile.hdf5', '/x', compression='lzf', shuffle=True)

In [4]: import h5py

In [5]: f = h5py.File('myfile.hdf5')

In [6]: dset = f['/x']

In [7]: dset
Out[7]: <HDF5 dataset "x": shape (100, 2048, 2048), type "<f8">

In [8]: dset.chunks
Out[8]: (5, 512, 512)

In [9]: import dask.array as da

In [10]: x = da.from_array(dset, chunks=(5, 512, 512))

In [11]: x
Out[11]: dask.array<from-ar..., shape=(100, 2048, 2048), dtype=float64, chunksize=(5, 512, 512)>

In [12]: a = x[0, :5, :5]

In [13]: b = x[:, :5, :5]

In [14]: c = a - b.mean()

In [15]: c.compute()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-0c5d552d1b01> in <module>()
----> 1 c.compute()

/usr/local/lib/python2.7/dist-packages/dask/base.pyc in compute(self, **kwargs)
     32 
     33     def compute(self, **kwargs):
---> 34         return compute(self, **kwargs)[0]
     35 
     36     @classmethod

/usr/local/lib/python2.7/dist-packages/dask/base.pyc in compute(*args, **kwargs)
    100                 for opt, val in groups.items()])
    101     keys = [arg._keys() for arg in args]
--> 102     results = get(dsk, keys, **kwargs)
    103     return tuple(a._finalize(a, r) for a, r in zip(args, results))
    104 

/usr/local/lib/python2.7/dist-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58 
     59     return results

/usr/local/lib/python2.7/dist-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    481                 _execute_task(task, data)  # Re-execute locally
    482             else:
--> 483                 raise(remote_exception(res, tb))
    484         state['cache'][key] = res
    485         finish_task(dsk, key, state, results, keyorder.get)

AttributeError: 'thread._local' object has no attribute 'astype'

Traceback
---------
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 244, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 245, in _execute_task
    return func(*args2)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 48, in getarray
    c = a[b]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 367, in __getitem__
    if self._local.astype is not None:


```

My system:

```
$ uname -a
Linux lealpc 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mrocklin** [comment]
My guess is that this is a thread safety issue.  What version of dask are you using?

```
>>> dask.__version__
```

**Comment by ricleal** [comment]
```
In [18]: dask.__version__
Out[18]: '0.7.5'
```

Just installed with pip...

**Comment by mrocklin** [comment]
If you have git installed then can I ask you to try this from git master and see if the problem persists?

```
$ pip install git+https://github.com/blaze/dask --upgrade
```

**Comment by ricleal** [comment]
I installed it from master but the problem persists :(

``` python
In [10]: c.compute()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-0c5d552d1b01> in <module>()
----> 1 c.compute()

/usr/local/lib/python2.7/dist-packages/dask/base.pyc in compute(self, **kwargs)
     35 
     36     def compute(self, **kwargs):
---> 37         return compute(self, **kwargs)[0]
     38 
     39     @classmethod

/usr/local/lib/python2.7/dist-packages/dask/base.pyc in compute(*args, **kwargs)
    108                 for opt, val in groups.items()])
    109     keys = [var._keys() for var in variables]
--> 110     results = get(dsk, keys, **kwargs)
    111 
    112     results_iter = iter(results)

/usr/local/lib/python2.7/dist-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58 
     59     return results

/usr/local/lib/python2.7/dist-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    479                 _execute_task(task, data)  # Re-execute locally
    480             else:
--> 481                 raise(remote_exception(res, tb))
    482         state['cache'][key] = res
    483         finish_task(dsk, key, state, results, keyorder.get)

AttributeError: 'thread._local' object has no attribute 'astype'

Traceback
---------
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 264, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 245, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 246, in _execute_task
    return func(*args2)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 48, in getarray
    c = a[b]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 367, in __getitem__
    if self._local.astype is not None:

```

**Comment by mrocklin** [comment]
OK, it looks like `da.from_array` has a `lock=` keyword argument.  My guess is that setting this to `True` should resolve this issue.  If so then we just need to update the example.

**Comment by ricleal** [comment]
I did what you suggested:

``` python
x = da.from_array(dset, chunks=(5, 512, 512), lock=True)
```

Still have the same error

**Comment by mrocklin** [comment]
Hrm, well then I'm confused.  The error here is coming from accessing an HDF5 file through `h5py` with many threads.   H5Py (and HDF5 generally) are not threadsafe but the lock we've added should ensure that no two threads interact with the h5py dataset at once.  

Unfortunately I'm unable to reproduce this error on my local machine running these versions

```
hdf5                      1.8.15.1                      1    <unknown>
h5py                      2.5.0                np19py34_3    <unknown>
numpy                     1.10.2                   py34_0    defaults
```

You can possibly sidestep this issue by turning off threading, though this will cause a performance hit.

``` python
import dask
dask.set_options(get=dask.async.get_sync)
```

**Comment by ricleal** [comment]
I'm using Python 2.7.11.
Ubuntu 14.04 comes with HDF5 1.8.11

I have just updated all the packages with PIP.

Those are my versions:

```
h5py.__version__
'2.2.1'

numpy.__version__
 '1.8.2'
```

I guess this is a problem with Ubuntu then... I will try to get the last HDF5 version and upgrade h5py.

**Comment by mrocklin** [comment]
I'm also on ubuntu 14.04

**Comment by ricleal** [comment]
Just removed the system `h5py` and installed the last version with PIP.
It works now!
Thanks

**Comment by mrocklin** [comment]
That's good to know and thank you for the error report.  We end up running into a lot of threading issues as various parts of the scipy ecosystem get stressed in this way for the first time.  It's invaluable to have people test, break things, and report back.

I see that you're at ORNL.  If you have the time and inclination I'd be curious to hear for what sorts of applications you think dask.array might be useful to you.

**Comment by ricleal** [comment]
I'm still doing some tests with dask+xray.
We have quite large MD datasets and I'm not sure yet if and how effectively we can use dask...
